### ISSUE TITLE
Posting Page

### ISSUE THREAD

**Issue by gabeholley222** [caydenreynolds/CS320_group_project#18]
Create HTML posting page structure.
Add CSS to posting page.

**Comment by gabeholley222** [comment]
HTML posting page structure is done. Still needs CSS to beautify the page.

**Comment by gabeholley222** [comment]
Created Posting Page template

**Comment by caydenreynolds** [comment]
Let's not close our issues until after we merge

**Comment by caydenreynolds** [comment]
Required for minimal working product

**Comment by gabeholley222** [comment]
Completed Selected Project HTML and Servlet
