### ISSUE TITLE
Submission Page

### ISSUE THREAD

**Issue by gabeholley222** [caydenreynolds/CS320_group_project#19]
Create HTML for Submission Page.
Add CSS to Submission Page.

**Comment by gabeholley222** [comment]
Created HTML layout for Submission Page.
Still needs CSS formatting.

**Comment by gabeholley222** [comment]
Created Submission Page template

**Comment by caydenreynolds** [comment]
Let's not close our issues until after we've merged

**Comment by caydenreynolds** [comment]
Required for minimum working product

**Comment by gabeholley222** [comment]
Completed Submission Servlet and HTML
