### ISSUE TITLE
Advanced search options

### ISSUE THREAD

**Issue by caydenreynolds** [caydenreynolds/CS320_group_project#90]
Search should allow selecting advanced options to query for projects
This will include adding new attributes to the project model. Be sure to update the UML accordingly

**Comment by gabeholley222** [comment]
Advanced Search to include Discipline(EE, ME, CE, and CS), archived, solicited, provided, poster.

**Comment by gabeholley222** [comment]
Also add sort project by date published.

**Comment by gabeholley222** [comment]
Also include Class(Fresh, Soph, Junior, Senior), skills, requirements, etc. Also include search matches somehow, someway... maybe in the project list as another display column? Prioritize by number of matches?

**Comment by gabeholley222** [comment]
Implemented searches for project attributes.
